### ISSUE TITLE
Contact Gerriet of IEM to inform him that the OSC is not being received properly in the IEM suite

### ISSUE THREAD

**Issue by AndrewRahman** [Spatial-Media-Lab/Max-OSC-Matrix#12]
Gerriet used to work at IEM and can forward our information along.

Let him know that the IEM plugin suite does not receive OSC packets just "FauxSC."

Email address is: sharma@gksh.net

**Comment by AndrewRahman** [comment]
Make sure to test ALL the other plugins before sending this email (so you don't look like a fool).

**Comment by fluesterTIMO** [comment]
IEM just released a new version. The channgelog says they added support for osc packets.

**Comment by AndrewRahman** [comment]
Already fixed for OSC 1.0
